openapi: 3.0.0
info:
  title: Minimal example
  version: 0.1.0
servers:
  - url: "http://localhost:8000"
paths:
  /ping:
    get:
      responses:
        '200':
          description: Returns `pong`
          content:
            text/plain:
              schema:
                type: string
              example: pong
